//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KRLab.Translations {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KRLab.Translations.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About KRLab 的本地化字符串。
        /// </summary>
        public static string AboutKRLab {
            get {
                return ResourceManager.GetString("AboutKRLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access 的本地化字符串。
        /// </summary>
        public static string Access {
            get {
                return ResourceManager.GetString("Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Aggregation 的本地化字符串。
        /// </summary>
        public static string AddNewAggregation {
            get {
                return ResourceManager.GetString("AddNewAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Association 的本地化字符串。
        /// </summary>
        public static string AddNewAssociation {
            get {
                return ResourceManager.GetString("AddNewAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New BNNode 的本地化字符串。
        /// </summary>
        public static string AddNewBNNode {
            get {
                return ResourceManager.GetString("AddNewBNNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New CMNode 的本地化字符串。
        /// </summary>
        public static string AddNewCMNode {
            get {
                return ResourceManager.GetString("AddNewCMNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Comment 的本地化字符串。
        /// </summary>
        public static string AddNewComment {
            get {
                return ResourceManager.GetString("AddNewComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Composition 的本地化字符串。
        /// </summary>
        public static string AddNewComposition {
            get {
                return ResourceManager.GetString("AddNewComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Delegate 的本地化字符串。
        /// </summary>
        public static string AddNewDelegate {
            get {
                return ResourceManager.GetString("AddNewDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Dependency 的本地化字符串。
        /// </summary>
        public static string AddNewDependency {
            get {
                return ResourceManager.GetString("AddNewDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Enum 的本地化字符串。
        /// </summary>
        public static string AddNewEnum {
            get {
                return ResourceManager.GetString("AddNewEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Generalization 的本地化字符串。
        /// </summary>
        public static string AddNewGeneralization {
            get {
                return ResourceManager.GetString("AddNewGeneralization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Interface 的本地化字符串。
        /// </summary>
        public static string AddNewInterface {
            get {
                return ResourceManager.GetString("AddNewInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add new item: 的本地化字符串。
        /// </summary>
        public static string AddNewItem {
            get {
                return ResourceManager.GetString("AddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Nesting 的本地化字符串。
        /// </summary>
        public static string AddNewNesting {
            get {
                return ResourceManager.GetString("AddNewNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Realization 的本地化字符串。
        /// </summary>
        public static string AddNewRealization {
            get {
                return ResourceManager.GetString("AddNewRealization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New SNNode 的本地化字符串。
        /// </summary>
        public static string AddNewSNNode {
            get {
                return ResourceManager.GetString("AddNewSNNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New Structure 的本地化字符串。
        /// </summary>
        public static string AddNewStructure {
            get {
                return ResourceManager.GetString("AddNewStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 « Right click here to add new project » 的本地化字符串。
        /// </summary>
        public static string AddProjectHint {
            get {
                return ResourceManager.GetString("AddProjectHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aggregation 的本地化字符串。
        /// </summary>
        public static string Aggregation {
            get {
                return ResourceManager.GetString("Aggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always 的本地化字符串。
        /// </summary>
        public static string Always {
            get {
                return ResourceManager.GetString("Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save changes to the following projects? 的本地化字符串。
        /// </summary>
        public static string AskSaveChanges {
            get {
                return ResourceManager.GetString("AskSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balazs Tihanyi 的本地化字符串。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Zoom 的本地化字符串。
        /// </summary>
        public static string AutoZoom {
            get {
                return ResourceManager.GetString("AutoZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beta version 的本地化字符串。
        /// </summary>
        public static string BetaVersion {
            get {
                return ResourceManager.GetString("BetaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add item 的本地化字符串。
        /// </summary>
        public static string ButtonAddItem {
            get {
                return ResourceManager.GetString("ButtonAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse... 的本地化字符串。
        /// </summary>
        public static string ButtonBrowse {
            get {
                return ResourceManager.GetString("ButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 的本地化字符串。
        /// </summary>
        public static string ButtonGenerate {
            get {
                return ResourceManager.GetString("ButtonGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        public static string ButtonLoad {
            get {
                return ResourceManager.GetString("ButtonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        public static string ButtonModify {
            get {
                return ResourceManager.GetString("ButtonModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page setup... 的本地化字符串。
        /// </summary>
        public static string ButtonPageSetup {
            get {
                return ResourceManager.GetString("ButtonPageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        public static string ButtonPrint {
            get {
                return ResourceManager.GetString("ButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select printer... 的本地化字符串。
        /// </summary>
        public static string ButtonSelectPrinter {
            get {
                return ResourceManager.GetString("ButtonSelectPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you change the inheritance modifier to abstract, the parent class will also become abstract. Do you want to continue? 的本地化字符串。
        /// </summary>
        public static string ChangingToAbstractConfirmation {
            get {
                return ResourceManager.GetString("ChangingToAbstractConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking for Updates 的本地化字符串。
        /// </summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 class 的本地化字符串。
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear recent files list 的本地化字符串。
        /// </summary>
        public static string ClearRecentList {
            get {
                return ResourceManager.GetString("ClearRecentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code Generation 的本地化字符串。
        /// </summary>
        public static string CodeGeneration {
            get {
                return ResourceManager.GetString("CodeGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code generation completed successfully. 的本地化字符串。
        /// </summary>
        public static string CodeGenerationCompleted {
            get {
                return ResourceManager.GetString("CodeGenerationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code generation failed. 的本地化字符串。
        /// </summary>
        public static string CodeGenerationFailed {
            get {
                return ResourceManager.GetString("CodeGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The output directory is not empty, the previous files will be overwritten.
        ///Do you still want to continue? 的本地化字符串。
        /// </summary>
        public static string CodeGenerationOverwriteConfirmation {
            get {
                return ResourceManager.GetString("CodeGenerationOverwriteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code style 的本地化字符串。
        /// </summary>
        public static string CodeStyle {
            get {
                return ResourceManager.GetString("CodeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command failed. 的本地化字符串。
        /// </summary>
        public static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment 的本地化字符串。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment Relationship 的本地化字符串。
        /// </summary>
        public static string CommentRelationship {
            get {
                return ResourceManager.GetString("CommentRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Composition 的本地化字符串。
        /// </summary>
        public static string Composition {
            get {
                return ResourceManager.GetString("Composition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmation 的本地化字符串。
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical Error 的本地化字符串。
        /// </summary>
        public static string CriticalError {
            get {
                return ResourceManager.GetString("CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected diagram element(s)? 的本地化字符串。
        /// </summary>
        public static string DeleteElementsConfirmation {
            get {
                return ResourceManager.GetString("DeleteElementsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected member? 的本地化字符串。
        /// </summary>
        public static string DeleteMemberConfirmation {
            get {
                return ResourceManager.GetString("DeleteMemberConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete {0}? 的本地化字符串。
        /// </summary>
        public static string DeleteProjectItemConfirmation {
            get {
                return ResourceManager.GetString("DeleteProjectItemConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete selected item(s) 的本地化字符串。
        /// </summary>
        public static string DeleteSelectedItems {
            get {
                return ResourceManager.GetString("DeleteSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dependency 的本地化字符串。
        /// </summary>
        public static string Dependency {
            get {
                return ResourceManager.GetString("Dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination: 的本地化字符串。
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagram 的本地化字符串。
        /// </summary>
        public static string Diagram {
            get {
                return ResourceManager.GetString("Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagram style 的本地化字符串。
        /// </summary>
        public static string DiagramStyle {
            get {
                return ResourceManager.GetString("DiagramStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double click here to add new diagram 的本地化字符串。
        /// </summary>
        public static string DoubleClickToAddDiagram {
            get {
                return ResourceManager.GetString("DoubleClickToAddDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 « Double click to edit » 的本地化字符串。
        /// </summary>
        public static string DoubleClickToEdit {
            get {
                return ResourceManager.GetString("DoubleClickToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Comment 的本地化字符串。
        /// </summary>
        public static string EditComment {
            get {
                return ResourceManager.GetString("EditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Relation 的本地化字符串。
        /// </summary>
        public static string EditRelation {
            get {
                return ResourceManager.GetString("EditRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit text: 的本地化字符串。
        /// </summary>
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid accessor modifier. 的本地化字符串。
        /// </summary>
        public static string ErrorAccessorModifier {
            get {
                return ResourceManager.GetString("ErrorAccessorModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name cannot be empty. 的本地化字符串。
        /// </summary>
        public static string ErrorBlankFilename {
            get {
                return ResourceManager.GetString("ErrorBlankFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add the same base interface. 的本地化字符串。
        /// </summary>
        public static string ErrorCannotAddSameBaseInterface {
            get {
                return ResourceManager.GetString("ErrorCannotAddSameBaseInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add the same interface. 的本地化字符串。
        /// </summary>
        public static string ErrorCannotAddSameInterface {
            get {
                return ResourceManager.GetString("ErrorCannotAddSameInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create delegates in {0}. 的本地化字符串。
        /// </summary>
        public static string ErrorCannotCrateDelegate {
            get {
                return ResourceManager.GetString("ErrorCannotCrateDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create relationship between the two objects. 的本地化字符串。
        /// </summary>
        public static string ErrorCannotCreateRelationship {
            get {
                return ResourceManager.GetString("ErrorCannotCreateRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create structures in {0}. 的本地化字符串。
        /// </summary>
        public static string ErrorCannotCreateStructure {
            get {
                return ResourceManager.GetString("ErrorCannotCreateStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot inherit from static or sealed class. 的本地化字符串。
        /// </summary>
        public static string ErrorCannotInherit {
            get {
                return ResourceManager.GetString("ErrorCannotInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot override non-virtual method. 的本地化字符串。
        /// </summary>
        public static string ErrorCannotOverride {
            get {
                return ResourceManager.GetString("ErrorCannotOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot save file with unspecified path. 的本地化字符串。
        /// </summary>
        public static string ErrorCannotSaveFile {
            get {
                return ResourceManager.GetString("ErrorCannotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set access modifier. 的本地化字符串。
        /// </summary>
        public static string ErrorCannotSetAccess {
            get {
                return ResourceManager.GetString("ErrorCannotSetAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set the modifier. 的本地化字符串。
        /// </summary>
        public static string ErrorCannotSetModifier {
            get {
                return ResourceManager.GetString("ErrorCannotSetModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set static modifier. 的本地化字符串。
        /// </summary>
        public static string ErrorCannotSetStatic {
            get {
                return ResourceManager.GetString("ErrorCannotSetStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set type. 的本地化字符串。
        /// </summary>
        public static string ErrorCannotSetType {
            get {
                return ResourceManager.GetString("ErrorCannotSetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not connect to the server. 的本地化字符串。
        /// </summary>
        public static string ErrorConnectToServer {
            get {
                return ResourceManager.GetString("ErrorConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructor&apos;s name does not equal with the class name. 的本地化字符串。
        /// </summary>
        public static string ErrorConstructorName {
            get {
                return ResourceManager.GetString("ErrorConstructorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The save file is corrupt and could not be loaded. 的本地化字符串。
        /// </summary>
        public static string ErrorCorruptSaveFile {
            get {
                return ResourceManager.GetString("ErrorCorruptSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Corrupt save format. 的本地化字符串。
        /// </summary>
        public static string ErrorCorruptSaveFormat {
            get {
                return ResourceManager.GetString("ErrorCorruptSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not load file. 的本地化字符串。
        /// </summary>
        public static string ErrorCouldNotLoadFile {
            get {
                return ResourceManager.GetString("ErrorCouldNotLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error while loading the plugins:
        ///{0} 的本地化字符串。
        /// </summary>
        public static string ErrorCouldNotLoadPlugins {
            get {
                return ResourceManager.GetString("ErrorCouldNotLoadPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not save file. 的本地化字符串。
        /// </summary>
        public static string ErrorCouldNotSaveFile {
            get {
                return ResourceManager.GetString("ErrorCouldNotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The base {0} is successor of the child {0}. 的本地化字符串。
        /// </summary>
        public static string ErrorCyclicBase {
            get {
                return ResourceManager.GetString("ErrorCyclicBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cyclic nesting relationships. 的本地化字符串。
        /// </summary>
        public static string ErrorCyclicNesting {
            get {
                return ResourceManager.GetString("ErrorCyclicNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destructor&apos;s name does not equal with the class name. 的本地化字符串。
        /// </summary>
        public static string ErrorDestructorName {
            get {
                return ResourceManager.GetString("ErrorDestructorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file name cannot be empty. 的本地化字符串。
        /// </summary>
        public static string ErrorEmptyFilename {
            get {
                return ResourceManager.GetString("ErrorEmptyFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} cannot be empty string. 的本地化字符串。
        /// </summary>
        public static string ErrorEmptyString {
            get {
                return ResourceManager.GetString("ErrorEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot implement explicitly. 的本地化字符串。
        /// </summary>
        public static string ErrorExplicitImplementation {
            get {
                return ResourceManager.GetString("ErrorExplicitImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set access modifier in explicit implementing. 的本地化字符串。
        /// </summary>
        public static string ErrorExplicitImplementationAccess {
            get {
                return ResourceManager.GetString("ErrorExplicitImplementationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found or no read permission. 的本地化字符串。
        /// </summary>
        public static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forbidden name. 的本地化字符串。
        /// </summary>
        public static string ErrorForbiddenName {
            get {
                return ResourceManager.GetString("ErrorForbiddenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forbidden type name. 的本地化字符串。
        /// </summary>
        public static string ErrorForbiddenTypeName {
            get {
                return ResourceManager.GetString("ErrorForbiddenTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The inner type is already nested. 的本地化字符串。
        /// </summary>
        public static string ErrorInnerTypeAlreadyNested {
            get {
                return ResourceManager.GetString("ErrorInnerTypeAlreadyNested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error in saving image. 的本地化字符串。
        /// </summary>
        public static string ErrorInSavingImage {
            get {
                return ResourceManager.GetString("ErrorInSavingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error in saving settings. 的本地化字符串。
        /// </summary>
        public static string ErrorInSavingSettings {
            get {
                return ResourceManager.GetString("ErrorInSavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The interface class is not {0} interface. 的本地化字符串。
        /// </summary>
        public static string ErrorInterfaceLanguage {
            get {
                return ResourceManager.GetString("ErrorInterfaceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot set accessibility of interface members. 的本地化字符串。
        /// </summary>
        public static string ErrorInterfaceMemberAccess {
            get {
                return ResourceManager.GetString("ErrorInterfaceMemberAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The base type is invalid. 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidBaseType {
            get {
                return ResourceManager.GetString("ErrorInvalidBaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid declaration. 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidDeclaration {
            get {
                return ResourceManager.GetString("ErrorInvalidDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid modifier. 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidModifier {
            get {
                return ResourceManager.GetString("ErrorInvalidModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} modifier is invalid with the {1} modifier. 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidModifierCombination {
            get {
                return ResourceManager.GetString("ErrorInvalidModifierCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid name. 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidName {
            get {
                return ResourceManager.GetString("ErrorInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid parameter declaration. 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidParameterDeclaration {
            get {
                return ResourceManager.GetString("ErrorInvalidParameterDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid type name. 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidTypeName {
            get {
                return ResourceManager.GetString("ErrorInvalidTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Languages do not equal. 的本地化字符串。
        /// </summary>
        public static string ErrorKRDoNotEqual {
            get {
                return ResourceManager.GetString("ErrorKRDoNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant variables must be initialized. 的本地化字符串。
        /// </summary>
        public static string ErrorLackOfInitialization {
            get {
                return ResourceManager.GetString("ErrorLackOfInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} type of member does not exist. 的本地化字符串。
        /// </summary>
        public static string ErrorMemberTypeDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorMemberTypeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple bases are not supported. 的本地化字符串。
        /// </summary>
        public static string ErrorMultipleBases {
            get {
                return ResourceManager.GetString("ErrorMultipleBases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent type does not support nesting. 的本地化字符串。
        /// </summary>
        public static string ErrorNestingNotSupported {
            get {
                return ResourceManager.GetString("ErrorNestingNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No printers are installed. 的本地化字符串。
        /// </summary>
        public static string ErrorNoPrinters {
            get {
                return ResourceManager.GetString("ErrorNoPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Derived type does not support generalization. 的本地化字符串。
        /// </summary>
        public static string ErrorNotAllowedChild {
            get {
                return ResourceManager.GetString("ErrorNotAllowedChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base type does not support generalization. 的本地化字符串。
        /// </summary>
        public static string ErrorNotAllowedParent {
            get {
                return ResourceManager.GetString("ErrorNotAllowedParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Implementer class cannot realize the interface. 的本地化字符串。
        /// </summary>
        public static string ErrorNotInterfaceImplementer {
            get {
                return ResourceManager.GetString("ErrorNotInterfaceImplementer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator method must be public. 的本地化字符串。
        /// </summary>
        public static string ErrorOperatorMustBePublic {
            get {
                return ResourceManager.GetString("ErrorOperatorMustBePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator method must be static. 的本地化字符串。
        /// </summary>
        public static string ErrorOperatorMustBeStatic {
            get {
                return ResourceManager.GetString("ErrorOperatorMustBeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter&apos;s type cannot be {0}. 的本地化字符串。
        /// </summary>
        public static string ErrorParameterType {
            get {
                return ResourceManager.GetString("ErrorParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was an error while printing:
        ///{0} 的本地化字符串。
        /// </summary>
        public static string ErrorPrinting {
            get {
                return ResourceManager.GetString("ErrorPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not read version data. 的本地化字符串。
        /// </summary>
        public static string ErrorReadVersionData {
            get {
                return ResourceManager.GetString("ErrorReadVersionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Types cannot contain themselves. 的本地化字符串。
        /// </summary>
        public static string ErrorRecursiveNesting {
            get {
                return ResourceManager.GetString("ErrorRecursiveNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified relationship does not exist. 的本地化字符串。
        /// </summary>
        public static string ErrorRelationshipDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorRelationshipDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a reserved name. 的本地化字符串。
        /// </summary>
        public static string ErrorReservedName {
            get {
                return ResourceManager.GetString("ErrorReservedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reason 的本地化字符串。
        /// </summary>
        public static string ErrorsReason {
            get {
                return ResourceManager.GetString("ErrorsReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static constructors must be parameterless. 的本地化字符串。
        /// </summary>
        public static string ErrorStaticConstructor {
            get {
                return ResourceManager.GetString("ErrorStaticConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indexer cannot be static. 的本地化字符串。
        /// </summary>
        public static string ErrorStaticIndexer {
            get {
                return ResourceManager.GetString("ErrorStaticIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interface members cannot be static. 的本地化字符串。
        /// </summary>
        public static string ErrorStaticInterfaceMember {
            get {
                return ResourceManager.GetString("ErrorStaticInterfaceMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type cannot be {0}. 的本地化字符串。
        /// </summary>
        public static string ErrorType {
            get {
                return ResourceManager.GetString("ErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} type does not exist. 的本地化字符串。
        /// </summary>
        public static string ErrorTypeDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorTypeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generalization 的本地化字符串。
        /// </summary>
        public static string Generalization {
            get {
                return ResourceManager.GetString("Generalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the target directory for the generated source files: 的本地化字符串。
        /// </summary>
        public static string GeneratorTargetDir {
            get {
                return ResourceManager.GetString("GeneratorTargetDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Implement explicitly 的本地化字符串。
        /// </summary>
        public static string ImplementExplicitly {
            get {
                return ResourceManager.GetString("ImplementExplicitly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Implementing 的本地化字符串。
        /// </summary>
        public static string Implementing {
            get {
                return ResourceManager.GetString("Implementing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import list 的本地化字符串。
        /// </summary>
        public static string ImportList {
            get {
                return ResourceManager.GetString("ImportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indent size: 的本地化字符串。
        /// </summary>
        public static string IndentSize {
            get {
                return ResourceManager.GetString("IndentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initial value 的本地化字符串。
        /// </summary>
        public static string InitialValue {
            get {
                return ResourceManager.GetString("InitialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 interface 的本地化字符串。
        /// </summary>
        public static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items of {0} 的本地化字符串。
        /// </summary>
        public static string ItemsOfType {
            get {
                return ResourceManager.GetString("ItemsOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} selected items. 的本地化字符串。
        /// </summary>
        public static string ItemsSelected {
            get {
                return ResourceManager.GetString("ItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KRLab Project Files 的本地化字符串。
        /// </summary>
        public static string LabProjectFiles {
            get {
                return ResourceManager.GetString("LabProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Members of {0} 的本地化字符串。
        /// </summary>
        public static string MembersOfType {
            get {
                return ResourceManager.GetString("MembersOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;About KRLab... 的本地化字符串。
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Add New 的本地化字符串。
        /// </summary>
        public static string MenuAddNew {
            get {
                return ResourceManager.GetString("MenuAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A&amp;ggregation 的本地化字符串。
        /// </summary>
        public static string MenuAggregation {
            get {
                return ResourceManager.GetString("MenuAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Align 的本地化字符串。
        /// </summary>
        public static string MenuAlign {
            get {
                return ResourceManager.GetString("MenuAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align &amp;Bottom 的本地化字符串。
        /// </summary>
        public static string MenuAlignBottom {
            get {
                return ResourceManager.GetString("MenuAlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align &amp;Horizontal Center 的本地化字符串。
        /// </summary>
        public static string MenuAlignHorizontal {
            get {
                return ResourceManager.GetString("MenuAlignHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align &amp;Left 的本地化字符串。
        /// </summary>
        public static string MenuAlignLeft {
            get {
                return ResourceManager.GetString("MenuAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align &amp;Right 的本地化字符串。
        /// </summary>
        public static string MenuAlignRight {
            get {
                return ResourceManager.GetString("MenuAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align &amp;Top 的本地化字符串。
        /// </summary>
        public static string MenuAlignTop {
            get {
                return ResourceManager.GetString("MenuAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align &amp;Vertical Center 的本地化字符串。
        /// </summary>
        public static string MenuAlignVertical {
            get {
                return ResourceManager.GetString("MenuAlignVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Association 的本地化字符串。
        /// </summary>
        public static string MenuAssociation {
            get {
                return ResourceManager.GetString("MenuAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto &amp;Height 的本地化字符串。
        /// </summary>
        public static string MenuAutoHeight {
            get {
                return ResourceManager.GetString("MenuAutoHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Auto routing 的本地化字符串。
        /// </summary>
        public static string MenuAutoRouting {
            get {
                return ResourceManager.GetString("MenuAutoRouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto &amp;Size 的本地化字符串。
        /// </summary>
        public static string MenuAutoSize {
            get {
                return ResourceManager.GetString("MenuAutoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto &amp;Width 的本地化字符串。
        /// </summary>
        public static string MenuAutoWidth {
            get {
                return ResourceManager.GetString("MenuAutoWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto &amp;Zoom 的本地化字符串。
        /// </summary>
        public static string MenuAutoZoom {
            get {
                return ResourceManager.GetString("MenuAutoZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Bidrectional 的本地化字符串。
        /// </summary>
        public static string MenuBidirectional {
            get {
                return ResourceManager.GetString("MenuBidirectional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;BN diagram 的本地化字符串。
        /// </summary>
        public static string MenuBNDiagram {
            get {
                return ResourceManager.GetString("MenuBNDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;BNNode 的本地化字符串。
        /// </summary>
        public static string MenuBNNode {
            get {
                return ResourceManager.GetString("MenuBNNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for &amp;Updates 的本地化字符串。
        /// </summary>
        public static string MenuCheckForUpdates {
            get {
                return ResourceManager.GetString("MenuCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Close {0} 的本地化字符串。
        /// </summary>
        public static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Close All Documents 的本地化字符串。
        /// </summary>
        public static string MenuCloseAllDocuments {
            get {
                return ResourceManager.GetString("MenuCloseAllDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close All P&amp;rojects 的本地化字符串。
        /// </summary>
        public static string MenuCloseAllProjects {
            get {
                return ResourceManager.GetString("MenuCloseAllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close All 的本地化字符串。
        /// </summary>
        public static string MenuCloseAllTabs {
            get {
                return ResourceManager.GetString("MenuCloseAllTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close All But This 的本地化字符串。
        /// </summary>
        public static string MenuCloseAllTabsButThis {
            get {
                return ResourceManager.GetString("MenuCloseAllTabsButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Close Project 的本地化字符串。
        /// </summary>
        public static string MenuCloseProject {
            get {
                return ResourceManager.GetString("MenuCloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string MenuCloseTab {
            get {
                return ResourceManager.GetString("MenuCloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;CM diagram 的本地化字符串。
        /// </summary>
        public static string MenuCMDiagram {
            get {
                return ResourceManager.GetString("MenuCMDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;CMNode 的本地化字符串。
        /// </summary>
        public static string MenuCMNode {
            get {
                return ResourceManager.GetString("MenuCMNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Collapse All 的本地化字符串。
        /// </summary>
        public static string MenuCollapseAll {
            get {
                return ResourceManager.GetString("MenuCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Collapse All Selected 的本地化字符串。
        /// </summary>
        public static string MenuCollapseAllSelected {
            get {
                return ResourceManager.GetString("MenuCollapseAllSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commen&amp;t 的本地化字符串。
        /// </summary>
        public static string MenuComment {
            get {
                return ResourceManager.GetString("MenuComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Co&amp;mment Relationship 的本地化字符串。
        /// </summary>
        public static string MenuCommentRelationship {
            get {
                return ResourceManager.GetString("MenuCommentRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C&amp;omposition 的本地化字符串。
        /// </summary>
        public static string MenuComposition {
            get {
                return ResourceManager.GetString("MenuComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Contents 的本地化字符串。
        /// </summary>
        public static string MenuContents {
            get {
                return ResourceManager.GetString("MenuContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Copy 的本地化字符串。
        /// </summary>
        public static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Copy to Clipboard as Image 的本地化字符串。
        /// </summary>
        public static string MenuCopyImageToClipboard {
            get {
                return ResourceManager.GetString("MenuCopyImageToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cu&amp;t 的本地化字符串。
        /// </summary>
        public static string MenuCut {
            get {
                return ResourceManager.GetString("MenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Delegate 的本地化字符串。
        /// </summary>
        public static string MenuDelegate {
            get {
                return ResourceManager.GetString("MenuDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Delete 的本地化字符串。
        /// </summary>
        public static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Delete From Project 的本地化字符串。
        /// </summary>
        public static string MenuDeleteProjectItem {
            get {
                return ResourceManager.GetString("MenuDeleteProjectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 De&amp;pendency 的本地化字符串。
        /// </summary>
        public static string MenuDependency {
            get {
                return ResourceManager.GetString("MenuDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Diagram 的本地化字符串。
        /// </summary>
        public static string MenuDiagram {
            get {
                return ResourceManager.GetString("MenuDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagram &amp;Navigator 的本地化字符串。
        /// </summary>
        public static string MenuDiagramNavigator {
            get {
                return ResourceManager.GetString("MenuDiagramNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Diagram Size... 的本地化字符串。
        /// </summary>
        public static string MenuDiagramSize {
            get {
                return ResourceManager.GetString("MenuDiagramSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Direction 的本地化字符串。
        /// </summary>
        public static string MenuDirection {
            get {
                return ResourceManager.GetString("MenuDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Edit 的本地化字符串。
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit... 的本地化字符串。
        /// </summary>
        public static string MenuEditAssociation {
            get {
                return ResourceManager.GetString("MenuEditAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Edit comment... 的本地化字符串。
        /// </summary>
        public static string MenuEditComment {
            get {
                return ResourceManager.GetString("MenuEditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Edit members... 的本地化字符串。
        /// </summary>
        public static string MenuEditMembers {
            get {
                return ResourceManager.GetString("MenuEditMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Enum 的本地化字符串。
        /// </summary>
        public static string MenuEnum {
            get {
                return ResourceManager.GetString("MenuEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E&amp;xit 的本地化字符串。
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Expand All 的本地化字符串。
        /// </summary>
        public static string MenuExpandAll {
            get {
                return ResourceManager.GetString("MenuExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Expand All Selected 的本地化字符串。
        /// </summary>
        public static string MenuExpandAllSelected {
            get {
                return ResourceManager.GetString("MenuExpandAllSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Export 的本地化字符串。
        /// </summary>
        public static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;File 的本地化字符串。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F&amp;ormat 的本地化字符串。
        /// </summary>
        public static string MenuFormat {
            get {
                return ResourceManager.GetString("MenuFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Genera&amp;lization 的本地化字符串。
        /// </summary>
        public static string MenuGeneralization {
            get {
                return ResourceManager.GetString("MenuGeneralization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Generate Code... 的本地化字符串。
        /// </summary>
        public static string MenuGenerateCode {
            get {
                return ResourceManager.GetString("MenuGenerateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Help 的本地化字符串。
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Import 的本地化字符串。
        /// </summary>
        public static string MenuImport {
            get {
                return ResourceManager.GetString("MenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Initial Value 的本地化字符串。
        /// </summary>
        public static string MenuInitialValue {
            get {
                return ResourceManager.GetString("MenuInitialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Interface 的本地化字符串。
        /// </summary>
        public static string MenuInterface {
            get {
                return ResourceManager.GetString("MenuInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Java diagram 的本地化字符串。
        /// </summary>
        public static string MenuJavaDiagram {
            get {
                return ResourceManager.GetString("MenuJavaDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Make Same Size 的本地化字符串。
        /// </summary>
        public static string MenuMakeSameSize {
            get {
                return ResourceManager.GetString("MenuMakeSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Member&apos;s Format 的本地化字符串。
        /// </summary>
        public static string MenuMembersFormat {
            get {
                return ResourceManager.GetString("MenuMembersFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Model &amp;Explorer 的本地化字符串。
        /// </summary>
        public static string MenuModelExplorer {
            get {
                return ResourceManager.GetString("MenuModelExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Nesting 的本地化字符串。
        /// </summary>
        public static string MenuNesting {
            get {
                return ResourceManager.GetString("MenuNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;New 的本地化字符串。
        /// </summary>
        public static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;New Project 的本地化字符串。
        /// </summary>
        public static string MenuNewProject {
            get {
                return ResourceManager.GetString("MenuNewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Open 的本地化字符串。
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;File... 的本地化字符串。
        /// </summary>
        public static string MenuOpenFile {
            get {
                return ResourceManager.GetString("MenuOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Options... 的本地化字符串。
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter &amp;Names 的本地化字符串。
        /// </summary>
        public static string MenuParameterNames {
            get {
                return ResourceManager.GetString("MenuParameterNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Parameters 的本地化字符串。
        /// </summary>
        public static string MenuParameters {
            get {
                return ResourceManager.GetString("MenuParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Paste 的本地化字符串。
        /// </summary>
        public static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Plugins 的本地化字符串。
        /// </summary>
        public static string MenuPlugins {
            get {
                return ResourceManager.GetString("MenuPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Print... 的本地化字符串。
        /// </summary>
        public static string MenuPrint {
            get {
                return ResourceManager.GetString("MenuPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Project 的本地化字符串。
        /// </summary>
        public static string MenuProject {
            get {
                return ResourceManager.GetString("MenuProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Properties 的本地化字符串。
        /// </summary>
        public static string MenuProperties {
            get {
                return ResourceManager.GetString("MenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Realization 的本地化字符串。
        /// </summary>
        public static string MenuRealization {
            get {
                return ResourceManager.GetString("MenuRealization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Redo 的本地化字符串。
        /// </summary>
        public static string MenuRedo {
            get {
                return ResourceManager.GetString("MenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Rename 的本地化字符串。
        /// </summary>
        public static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse 的本地化字符串。
        /// </summary>
        public static string MenuReverse {
            get {
                return ResourceManager.GetString("MenuReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same &amp;Height 的本地化字符串。
        /// </summary>
        public static string MenuSameHeight {
            get {
                return ResourceManager.GetString("MenuSameHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Same Size 的本地化字符串。
        /// </summary>
        public static string MenuSameSize {
            get {
                return ResourceManager.GetString("MenuSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same &amp;Width 的本地化字符串。
        /// </summary>
        public static string MenuSameWidth {
            get {
                return ResourceManager.GetString("MenuSameWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Save 的本地化字符串。
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sa&amp;ve All Projects 的本地化字符串。
        /// </summary>
        public static string MenuSaveAllProjects {
            get {
                return ResourceManager.GetString("MenuSaveAllProjects", resourceCulture);
            }
        }
         
        
        /// <summary>
        ///   查找类似 Save &amp;As... 的本地化字符串。
        /// </summary>
        public static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Save As Image... 的本地化字符串。
        /// </summary>
        public static string MenuSaveAsImage {
            get {
                return ResourceManager.GetString("MenuSaveAsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Save {0} 的本地化字符串。
        /// </summary>
        public static string MenuSaveProject {
            get {
                return ResourceManager.GetString("MenuSaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save {0} &amp;As... 的本地化字符串。
        /// </summary>
        public static string MenuSaveProjectAs {
            get {
                return ResourceManager.GetString("MenuSaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Save Selection as Image... 的本地化字符串。
        /// </summary>
        public static string MenuSaveSelectionAsImage {
            get {
                return ResourceManager.GetString("MenuSaveSelectionAsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Select All 的本地化字符串。
        /// </summary>
        public static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Size 的本地化字符串。
        /// </summary>
        public static string MenuSize {
            get {
                return ResourceManager.GetString("MenuSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;SN diagram 的本地化字符串。
        /// </summary>
        public static string MenuSNDiagram {
            get {
                return ResourceManager.GetString("MenuSNDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;SNNode 的本地化字符串。
        /// </summary>
        public static string MenuSNNode {
            get {
                return ResourceManager.GetString("MenuSNNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Structure 的本地化字符串。
        /// </summary>
        public static string MenuStruct {
            get {
                return ResourceManager.GetString("MenuStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Type 的本地化字符串。
        /// </summary>
        public static string MenuType {
            get {
                return ResourceManager.GetString("MenuType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Undo 的本地化字符串。
        /// </summary>
        public static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Unidirectional 的本地化字符串。
        /// </summary>
        public static string MenuUnidirectional {
            get {
                return ResourceManager.GetString("MenuUnidirectional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;View 的本地化字符串。
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Zoom 的本地化字符串。
        /// </summary>
        public static string MenuZoom {
            get {
                return ResourceManager.GetString("MenuZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom &amp;In 的本地化字符串。
        /// </summary>
        public static string MenuZoomIn {
            get {
                return ResourceManager.GetString("MenuZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom &amp;Out 的本地化字符串。
        /// </summary>
        public static string MenuZoomOut {
            get {
                return ResourceManager.GetString("MenuZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modifier: 的本地化字符串。
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modifiers 的本地化字符串。
        /// </summary>
        public static string Modifiers {
            get {
                return ResourceManager.GetString("Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify item: 的本地化字符串。
        /// </summary>
        public static string ModifyItem {
            get {
                return ResourceManager.GetString("ModifyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Down 的本地化字符串。
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Up 的本地化字符串。
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nesting 的本地化字符串。
        /// </summary>
        public static string Nesting {
            get {
                return ResourceManager.GetString("Nesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Never 的本地化字符串。
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Constructor 的本地化字符串。
        /// </summary>
        public static string NewConstructor {
            get {
                return ResourceManager.GetString("NewConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Destructor 的本地化字符串。
        /// </summary>
        public static string NewDestructor {
            get {
                return ResourceManager.GetString("NewDestructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Event 的本地化字符串。
        /// </summary>
        public static string NewEvent {
            get {
                return ResourceManager.GetString("NewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Field 的本地化字符串。
        /// </summary>
        public static string NewField {
            get {
                return ResourceManager.GetString("NewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Method 的本地化字符串。
        /// </summary>
        public static string NewMethod {
            get {
                return ResourceManager.GetString("NewMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Parameter 的本地化字符串。
        /// </summary>
        public static string NewParameter {
            get {
                return ResourceManager.GetString("NewParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Property 的本地化字符串。
        /// </summary>
        public static string NewProperty {
            get {
                return ResourceManager.GetString("NewProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Value 的本地化字符串。
        /// </summary>
        public static string NewValue {
            get {
                return ResourceManager.GetString("NewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version released 的本地化字符串。
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This function is not yet implemented. 的本地化字符串。
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No updates are avaiable. 的本地化字符串。
        /// </summary>
        public static string NoUpdates {
            get {
                return ResourceManager.GetString("NoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Override Members 的本地化字符串。
        /// </summary>
        public static string OverrideMembers {
            get {
                return ResourceManager.GetString("OverrideMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pages: 的本地化字符串。
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} by {1} 的本地化字符串。
        /// </summary>
        public static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous File Formats 的本地化字符串。
        /// </summary>
        public static string PreviousFileFormats {
            get {
                return ResourceManager.GetString("PreviousFileFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print only selected elements 的本地化字符串。
        /// </summary>
        public static string PrintOnlySelectedElements {
            get {
                return ResourceManager.GetString("PrintOnlySelectedElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to download the update now? 的本地化字符串。
        /// </summary>
        public static string ProgramDownload {
            get {
                return ResourceManager.GetString("ProgramDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A critical error has occurred, the program must be terminated.
        ///A crash log and recovery files have been created in the Application Data directory. 的本地化字符串。
        /// </summary>
        public static string ProgramTerminates {
            get {
                return ResourceManager.GetString("ProgramTerminates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read-only 的本地化字符串。
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read-Write 的本地化字符串。
        /// </summary>
        public static string ReadWrite {
            get {
                return ResourceManager.GetString("ReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Realization 的本地化字符串。
        /// </summary>
        public static string Realization {
            get {
                return ResourceManager.GetString("Realization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember open projects on close 的本地化字符串。
        /// </summary>
        public static string RememberOpenProjects {
            get {
                return ResourceManager.GetString("RememberOpenProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This program requires the .NET 2.0 Framework.
        ///Please download and install the .NET Framework and run this setup again.
        ///Do you want to download the framework now? 的本地化字符串。
        /// </summary>
        public static string RequiresNetFramework {
            get {
                return ResourceManager.GetString("RequiresNetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changing the language requires application restart. 的本地化字符串。
        /// </summary>
        public static string RequiresRestart {
            get {
                return ResourceManager.GetString("RequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return type: 的本地化字符串。
        /// </summary>
        public static string ReturnType {
            get {
                return ResourceManager.GetString("ReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As 的本地化字符串。
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As Image 的本地化字符串。
        /// </summary>
        public static string SaveAsImage {
            get {
                return ResourceManager.GetString("SaveAsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file has been changed. Would you like to save the changes? 的本地化字符串。
        /// </summary>
        public static string SaveChangesConfirmation {
            get {
                return ResourceManager.GetString("SaveChangesConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send e-mail to the program&apos;s author 的本地化字符串。
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please send this file to the address &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string SendLogFile {
            get {
                return ResourceManager.GetString("SendLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show chevron button: 的本地化字符串。
        /// </summary>
        public static string ShowChevron {
            get {
                return ResourceManager.GetString("ShowChevron", resourceCulture);
            }
        }
                
                
        /// <summary>
        ///   查找类似 SNISA Relationship 的本地化字符串。
        /// </summary>
        public static string SNRelationship {
            get {
                return ResourceManager.GetString("SNRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type of solution file: 的本地化字符串。
        /// </summary>
        public static string SolutionType {
            get {
                return ResourceManager.GetString("SolutionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort by Access 的本地化字符串。
        /// </summary>
        public static string SortByAccess {
            get {
                return ResourceManager.GetString("SortByAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort by Kind 的本地化字符串。
        /// </summary>
        public static string SortByKind {
            get {
                return ResourceManager.GetString("SortByKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort by Name 的本地化字符串。
        /// </summary>
        public static string SortByName {
            get {
                return ResourceManager.GetString("SortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Start menu group 的本地化字符串。
        /// </summary>
        public static string StartMenuGroup {
            get {
                return ResourceManager.GetString("StartMenuGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Style 的本地化字符串。
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Syntax 的本地化字符串。
        /// </summary>
        public static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string TranslationName {
            get {
                return ResourceManager.GetString("TranslationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English translation has been updated. 的本地化字符串。
        /// </summary>
        public static string TranslationUpdated {
            get {
                return ResourceManager.GetString("TranslationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2009-08-26 的本地化字符串。
        /// </summary>
        public static string TranslationVersion {
            get {
                return ResourceManager.GetString("TranslationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall 的本地化字符串。
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown error 的本地化字符串。
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Untitled 的本地化字符串。
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use ClearType 的本地化字符串。
        /// </summary>
        public static string UseClearType {
            get {
                return ResourceManager.GetString("UseClearType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In exported images (disables transparency) 的本地化字符串。
        /// </summary>
        public static string UseClearTypeForImages {
            get {
                return ResourceManager.GetString("UseClearTypeForImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill methods with &apos;Not implemented&apos; exceptions 的本地化字符串。
        /// </summary>
        public static string UseNotImplementedExceptions {
            get {
                return ResourceManager.GetString("UseNotImplementedExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use precision snapping 的本地化字符串。
        /// </summary>
        public static string UseSnapping {
            get {
                return ResourceManager.GetString("UseSnapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use tabs for indents 的本地化字符串。
        /// </summary>
        public static string UseTabs {
            get {
                return ResourceManager.GetString("UseTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit program&apos;s homepage 的本地化字符串。
        /// </summary>
        public static string VisitHomepage {
            get {
                return ResourceManager.GetString("VisitHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When mouse hovers 的本地化字符串。
        /// </summary>
        public static string WhenMouseHovers {
            get {
                return ResourceManager.GetString("WhenMouseHovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When zoomed in/out 的本地化字符串。
        /// </summary>
        public static string WhenZoomed {
            get {
                return ResourceManager.GetString("WhenZoomed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write-only 的本地化字符串。
        /// </summary>
        public static string WriteOnly {
            get {
                return ResourceManager.GetString("WriteOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom In 的本地化字符串。
        /// </summary>
        public static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom Out 的本地化字符串。
        /// </summary>
        public static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
